# FROM golang:1.26

# RUN apt-get update && apt-get install -y build-essential

# WORKDIR /app

# COPY . .

# ENV CGO_ENABLED=1
# ENV GOOS=linux
# ENV GOARCH=amd64

# RUN go mod tidy

# RUN go build -buildmode=plugin -o backend.so

FROM heroiclabs/nakama-pluginbuilder:3.38.0 AS builder

WORKDIR /backend
COPY . .

RUN go mod tidy
RUN go build --trimpath --buildmode=plugin -o backend.so

FROM alpine:3.20
WORKDIR /
COPY --from=builder /backend/backend.so /backend.so
CMD ["sh"]